apiVersion: v1
kind: Service
metadata:
  name: simple-load-balancer-service
  labels:
    app: simple-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: simple-load-balancer